### ISSUE TITLE
Doesn't read 0xffffff values

### ISSUE THREAD

**Issue by roblav96** [braver/ColorHints#2]
I was editing my [Alacritty](https://github.com/jwilm/alacritty) config colors and they use the `0xffffff` format which ColorHints wasn't able to read.

## Example:
```yaml
background: '0x000000'
```
[alacritty.yml#L187](https://github.com/jwilm/alacritty/blob/86b9cdbabe495effed3559d2561f65efab9becaa/alacritty.yml#L187)

**Comment by braver** [comment]
So, it’s `0x` to indicate it’s a hexadecimal value, and then it’s basically just like CSS hex colors? Always with 6 positions, or is 3 also valid (e.g. 0x000 for black)?

**Comment by roblav96** [comment]
@braver The revision https://github.com/braver/ColorHints/commit/f0622559b32377e75f2a51a5524db3db5ff7f2dd works like a charm! Thanks friend =]

**Comment by braver** [comment]
👌🏻
