### ISSUE TITLE
Shows wrong colors for hex codes with alpha

### ISSUE THREAD

**Issue by YBPN** [braver/ColorHints#3]
This is on Sublime Text 4113.

#08F4 is shown as bright green, and #FFAA0040 is shown as blood red.

When a hex code has alpha, it looks like it ignores the Red value and interprets the Green/Blue/Alpha as RGB. So #08F4 is interpreted as #8F4.

**Comment by braver** [comment]
Ah, yes, it seems to be treating the leading characters as the alpha instead of the trailing ones. 🤔 Let's see what we can do about that.
