### ISSUE TITLE
Update RAL colors

### ISSUE THREAD

**Issue by jrappen** [braver/ColorHints#5]
Update RAL colors to the ones currently available:

<https://www.ral-farben.de/en/all-ral-colours>

I extracted them into formatted JSON files:

~~ral-colors.zip~~

**Comment by braver** [comment]
Cool!

**Comment by jrappen** [comment]
- fix escapes
- convert colors from hex to rgb
- prettify colors array

~~ral-colors.zip~~

**Comment by jrappen** [comment]
* added RAL plastics

[ral-colors.zip](https://github.com/braver/ColorHints/files/10791590/ral-colors.zip)

**Comment by braver** [comment]
I ended up scraping that page and simply completed the lookup map I already had.
